### ISSUE TITLE
Add a customization for electric-indent-mode?

### ISSUE THREAD

**Issue by hartzell** [rdallasgray/graphene#23]
electric-indent-mode drives a couple of my major modes crazy (e.g. Markdown).

I can live without it, and disabling it locally once it's enabled globally is [messy](http://stackoverflow.com/questions/21182550/how-to-turn-of-electric-indent-mode-for-specific-major-mode/21183089#21183089).

Are you open to adding a something to graphene.el like this:

```lisp
(defcustom graphene-electric-indent-mode-auto t
  "Whether graphene should enable electric-indent-mode with prog-modes."
  :type 'boolean
  :group 'graphene)
```

and 

changing the lambda that's added to graphene-prog-mode-hook in graphene-editing.el from this

```lisp
          (electric-indent-mode 1)))
```

to something like

```
    (when graphene-electric-indent-mode-auto
      (electric-indent-mode 1))))
```

**Comment by rdallasgray** [comment]
Hi George -- for sure, although I'd call the custom setting `graphene-autoindent` to maintain separation from the particular indentation package.

**Comment by hartzell** [comment]
As long as you document it clearly, that'd make sense.

Emacs seems to have a plethora of modes that automatically cause indentation to happen, and the one in particular that it problematic is electric-indent-mode.  If you're clear that electric-indent-mode is what's being disabled, and that it has nothing to do with e.g. auto-indent-mode.el then it'll work fine.

Thanks!

**Comment by rdallasgray** [comment]
Should be fixed by https://github.com/rdallasgray/graphene/blob/master/graphene-editing.el#L54
