### ISSUE TITLE
Initial frame too large the first time graphene is run

### ISSUE THREAD

**Issue by rodprice** [rdallasgray/graphene#28]
The first time I start Emacs with graphene, the initial frame is too large for my small screen. The minibuffer is off-screen, and I cannot drag the frame handle (Windows 7) to resize the Emacs frame so that I can see the minibuffer. A more conservative initial setting, say, (100 40 0 0) rather than (140 60 0 0) in graphene-load-frame-geometry, would solve the problem. As it is, I edited .graphene-geometry by hand and all worked fine afterward. Thanks.

**Comment by rdallasgray** [comment]
Should be taken care of in https://github.com/rdallasgray/graphene/commit/edca4f634aa1f99092d6166b7fac19dec7a506d2
