### ISSUE TITLE
Completion needs an inferior Python process running

### ISSUE THREAD

**Issue by michaelsilver** [rdallasgray/graphene#30]
When editing a python file, emacs complains "Completion needs an inferior Python process running":
<img width="742" alt="screen shot 2015-12-28 at 7 06 51 pm" src="https://cloud.githubusercontent.com/assets/5913522/12023922/9fc1463c-ad96-11e5-9ac2-8746ca30dad3.png">
I've made hardly any [customizations](https://github.com/michaelsilver/emacs-config) on top of graphene, none of which I think should be related in any way. Any help would be appreciated. Thanks!

**Comment by rdallasgray** [comment]
I think this is probably related to company-mode's Python completion, and not a graphene issue - but please feel free to reopen if you disagree after checking.
