### ISSUE TITLE
Graphene 'replaces' current theme with graphene-meta-theme upon sta

### ISSUE THREAD

**Issue by aaronhyperum** [rdallasgray/graphene#31]
On my Mac, Graphene unchecks the current theme and checks its own meta theme causing the color theme to be the default, out-of-the-box one.

**Comment by rdallasgray** [comment]
Hi Aaron - can you show me the code you're using to load graphene and your theme?

**Comment by aaronhyperum** [comment]
I've actually got it fixed now: before, I used to load my themes through the customize-themes menu. Now, I just have to load it through .vimrc as Graphene replaces it. Maybe this is intended behaviour. But I've found a workaround either way.
