### ISSUE TITLE
installing graphene deleted my existing .emacs

### ISSUE THREAD

**Issue by brlcad** [rdallasgray/graphene#40]
Nowhere in the docs or installation instructions did it mention that installing graphene was going to blow away my existing .emacs configuration.  If there was some technical requirement for it, I should have been queried or at least informed during the installation process that that was going to happen.  I had to recover from my own backup (which graphene's installation did not make prior to deletion) and restore my plethora of scripts, macros, and settings which graphene had no business deleting. 

I was excited to give graphene a trial run, but that behavior is outright rude behavior to users and not something I care to endorse or support.

**Comment by rdallasgray** [comment]
Hi — sorry to hear you’ve had some trouble, but there is no ‘installation process’ for graphene beyond the package install and it certainly does not delete your files (I doubt that’s even possible). I’m afraid something unrelated to graphene must have happened.

**Comment by brlcad** [comment]
What I took to be instructions were from the Installation section of your README.md.  Namely, I added:

```
;; Require Emacs' package functionality
(require 'package)

;; Add the Melpa repository to the list of package sources
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)

;; Initialise the package system.
(package-initialize)
```

to my .emacs, selected those lines, ran M-x eval-region, M-x list-packages, selected graphene for installation, installed it, restarted emacs, and my .emacs was gone.

**Comment by brlcad** [comment]
Perhaps initializing the package system did the deletion or has some bug if it's already initialized or tried to convert it into init.el and failed... I don't know.  Apologies for attributing to Graphene if this was a package system bug, but I was unhappy to find it gone after following your README.md and obviously attributed it to graphene as a result.

**Comment by rdallasgray** [comment]
No problem. It might help if you try to reproduce the issue and see if you can figure out what’s responsible, it could be a bug somewhere else. I’m confident it’s not graphene per se, at least in part because this is the only such report I’ve had in about ten years and several thousand installations!

**Comment by brlcad** [comment]
UPDATE: I think I've narrowed in on a cause as I have files getting deleted on me left and right with graphene enabled.  There appears to be some behavior or key binding that is deleting the currently visited buffer when I switch to another via C-x C-v.  With default bindings, one does C-x C-v, C-k to cut the path in order to type a new file name.  Either graphene or some sub-package graphene is loading appears to be changing that mini-buffer navigation that makes it trivial to delete files (perhaps by pressing k or backspace or some other binding?)  I haven't narrowed on the specific sequence, but I'm definitely deleting just by switching files due to something new enabled.  Any ideas?

**Comment by rdallasgray** [comment]
You could investigate what the key sequences in question are bound to?

**Comment by brlcad** [comment]
I'm not sure how to go about doing that as I'm already in the mini buffer and can't query M-x describe key.  I'll see if I can figure out a specific sequence to see if you can reproduce it.

**Comment by brlcad** [comment]
What is the package that changed the find alternative file behavior?  If it's an intentional convenience setting, it may be documented.  Might just happen to be tripping up on how I rapidly switch among files and dirs, and some mini-buffer binding is deleting the active buffer file or path displayed in the mini buffer.

**Comment by rdallasgray** [comment]
I think you should be able to find that out using describe-function — I’m afraid I can’t really help more with this, until you can demonstrate that it’s caused specifically by graphene. Thanks and all best.
