### ISSUE TITLE
After installing Graphene, Ido is deleting my files without confirmation

### ISSUE THREAD

**Issue by brlcad** [rdallasgray/graphene#42]
I was able to pinpoint the cause of issue #40 .  If you touch file1 file2; emacs file1; and C-x C-v C-k file2 to switch to file2 (as was the minimal sequence with default emacs), it ends up deleting file1.  Describing C-x C-v, I see it's been rebound to ido-find-alternate-file, so Graphene's embracing of Ido appears to be the source of heartburn.

Reading up in ido.el, I found a relevant comment:

```
  144 ;; Additional functionality                                               
  145 ;; ------------------------                                               
  146 ;;                                                                        
  147 ;; After C-x b, the buffer at the head of the list can be killed by       
  148 ;; pressing C-k.  If the buffer needs saving, you will be queried         
  149 ;; before the buffer is killed.                                           
  150 ;;                                                                        
  151 ;; Likewise, after C-x C-f, you can delete (i.e. physically remove)       
  152 ;; the file at the head of the list with C-k.  You will always be         
  153 ;; asked for confirmation before the file is deleted.
```

So Ido says it should've asked for confirmation but apparently doesn't.  Perhaps Graphene configured Ido to not prompt confirmation, perhaps an Ido bug.  This is obviously only Graphene's problem from a parent package perspective, by the nature of Graphene enabling and/or possibly configuring Ido.

Is there an easy way to configure Ido off or the deletion confirmation on, but leave the rest of Graphene and other packages enabled?

I can't be accidentally deleting files just by switching buffers, so this may be an impasse until it's fixed or my fingers are retrained, neither likely happening soon.  Thank you again for your help sorting this all out.

**Comment by rdallasgray** [comment]
All the config that graphene sets for ido is here: https://github.com/rdallasgray/graphene/blob/master/graphene-env.el

You’re of course free to simply turn ido off after requiring graphene, and it would probably make sense to raise this as an issue in the ido repo.
